### ISSUE TITLE
Add MixPanel

### ISSUE THREAD

**Issue by key88sf** [jkrall/analytical#1]
Would be nice to add MixPanel support as well.

**Comment by jkrall** [comment]
I agree!  I don't use mixpanel though... so it didn't make my initial list.  

If you need it... send me a request and I'll be glad to pull it in.  It should be pretty easy to implement, check out the KISSMetrics module and let me know if you need any guidance.

**Comment by jkrall** [comment]
Oops... forgot to close this.  Mixpanel support made it in here:
https://github.com/jkrall/analytical/commit/80733a515d1fd1bd83634c2bcce3a6f674e0674a
