### ISSUE TITLE
analytical 2.7 broke Rails 3 support

### ISSUE THREAD

**Issue by nirvdrum** [jkrall/analytical#13]
Starting with analytical 2.7, there are a lot more dependencies listed in the gemspec.  My guess is these were added by one of the new modules.  In any event, analytical now only works with Rails 2.x, for x >= 3 and will not load up in Rails 3.

**Comment by jkrall** [comment]
Whoops... Yeah, it looks like jeweler screwed me over.  I added a gemfile, which I mistakenly assumed would only be used for gem development... But apparently jeweler added everything to the gemspec.

Sorry, will fix today and release a new version!

**Comment by jkrall** [comment]
Fixed gem dependencies, Version bump to 2.7.2
Closed by e0be347fe9678f9bc577ff49217270df605f00b6
