### ISSUE TITLE
Console breaks if you don't use Prototype

### ISSUE THREAD

**Issue by ChrisRicca** [jkrall/analytical#2]
Specifically, you can't do: $H(#{data.to_json}).toJSON()

**Comment by ChrisRicca** [comment]
Will look for an alternative way of JSON-ifying the data when I get a chance, but for now wanted to note issue here.

**Comment by jkrall** [comment]
Simple fix to console module, so that Prototype
$H() isn't required.   Closed by 6647edf7a02adafbb7b539b077bd102fb3353edc
