### ISSUE TITLE
Analytical helper not loading in rails

### ISSUE THREAD

**Issue by gsiener** [jkrall/analytical#39]
We had been using the analytical gem circa version 2 and recently upgraded to 3.0.12.  It appears that the view helper wasn't loading correctly, giving the following error:
`undefined local variable or method 'analytical' for #<#<Class:0x10a261b18>:0x10a251560>`

Adding `helper_method :analytical` to our application_controller.rb fixed this issue.  We are on rails 3.1.3.

**Comment by sfsekaran** [comment]
This seems like it's a duplicate of #38. Can you confirm this, @gsiener? Perhaps provide a failing spec? Thanks!

**Comment by gsiener** [comment]
I'm no longer involved with the project that I originally filed this for, but the workaround I mentioned above did sort everything out.  Closing.
