### ISSUE TITLE
Clicky data collection is empty

### ISSUE THREAD

**Issue by lgs** [jkrall/analytical#42]
After following the Readme and configuring Clicky provider only, my data collection is empty. 

Do you have suggestions to troubleshoot this ? 

This is my HTML generated by HAML on Rails 3.2.2 : https://gist.github.com/2135704

**Comment by jkrall** [comment]
Looks OK to me at a glance.  Maybe compare the HTML output with the snippet that Clicky is asking you to install to make sure nothing has changed and needs to be updated in the Clicky module...

**Comment by lgs** [comment]
... ok the README say:  Add a configuration file (config/analytical.yml) to declare your API keys, like so:

<pre>
production:
  google:
    key: UA-5555555-5
  clicky:
    key: 55555
development:
test:
</pre> 


but the provider specify : Site ID, Site key  and Admin site key, and I exchanged  Site ID with Site key my fault, sorry. 

Luca
