### ISSUE TITLE
Support for Gauges

### ISSUE THREAD

**Issue by sfsekaran** [jkrall/analytical#43]
http://get.gaug.es/

I notice it being used much more frequently lately, and it has some pretty good reviews. Might be worth adding to Analytical.

**Comment by jkrall** [comment]
Sure, I agree!  Care to submit a patch?

**Comment by sfsekaran** [comment]
I would love to. I'll try my best to eek out some time, but I don't want to stop someone else from picking this up if I don't get to it.

**Comment by sfsekaran** [comment]
I've submitted pull request #44 which implements Gauges functionality. Closing this issue in favor of that one.
