### ISSUE TITLE
Print warning if :development_modules is still used

### ISSUE THREAD

**Issue by nirvdrum** [jkrall/analytical#46]
I'm really late to the game on this one, but I've just now realized that :development_modules does nothing since version 2.11.0.  As a result, I've been storing crap data in my various analytics providers for over a year.  Naturally, this is problematic and broke pretty heavily with the backwards compatibility note in the README.

**Comment by sfsekaran** [comment]
Understood. Not much we can do now, but If you think it's appropriate to bring this feature back, we can discuss and potentially reopen this.
