### ISSUE TITLE
Update rubygems version to 3.0.13 or 3.1.0 or something

### ISSUE THREAD

**Issue by sfsekaran** [jkrall/analytical#59]
It's been a year since the last gem version, so maybe it's prudent. That is unless everyone else uses the github version anyway, in which case nevermind :8ball:

**Comment by sfsekaran** [comment]
@jkrall May I have access to push to rubygems for analytical?

**Comment by jellybob** [comment]
+1

**Comment by jkrall** [comment]
Wow I don't know how I missed this issue... sorry.

@sfsekaran I need your email on rubygems to add you, it seems.  Can you send it to me?  
"joshuakrall at pobox.com"

**Comment by sfsekaran** [comment]
Done!

—
Sathya Sekaran
