### ISSUE TITLE
Wiki Page for KissMetrics

### ISSUE THREAD

**Issue by gyarra** [jkrall/analytical#62]
Hi,

I created a Wiki Page to help KissMetrics users migrate to Analytical. There are a couple things I still want to add, but I do think it's useful as is.
https://github.com/gyarra/analytical/wiki/KissMetrics

I'd like to add a page like this for every package I'm familiar with.

If you enable wiki pages for the project I can add it directly.

Thanks!
Gabe

**Comment by sfsekaran** [comment]
It should be there. Let us know if you still can't access it.

**Comment by sfsekaran** [comment]
Closing this as the wiki pages are up.
