### ISSUE TITLE
First line in header causes "undefined method `merge' for nil:NilClass" 

### ISSUE THREAD

**Issue by ACPK** [jkrall/analytical#74]
Since we use HAML, I added the line below to the beginning of my header but it causes an "undefined merge issue".

 = raw analytical.head_prepend_javascript

**Comment by sfsekaran** [comment]
Can you reproduce it in a newly generated rails app?

**Comment by tristanm** [comment]
I ran into this issue when the `analytical` macro hadn't been called on a particular controller that didn't inherit from `ApplicationController`. For me the fix was simple: make sure `analytical` was called in all controllers, not just those inheriting from `ApplicationController`.

**Comment by sfsekaran** [comment]
Makes sense. Closing this for now. If anyone has a good workaround or a better error message for analytical.head_prepend_javascript, please send in a pull request!
