### ISSUE TITLE
Update Google Analytics Tracking Code

### ISSUE THREAD

**Issue by Epiju** [jkrall/analytical#75]
Hi!

I'm using analytical in my application but I have to update the google analytics tracking code (https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad).
How can I do that?

Thanks!

**Comment by sfsekaran** [comment]
Have you tried overriding the google analytics embed code with your custom variation?

**Comment by pejmanjohn** [comment]
I'm facing the same issue. How does one override the embed code?

The update is changing this line: ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

To this: ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
