### ISSUE TITLE
Dynamical create account

### ISSUE THREAD

**Issue by richardrails** [jkrall/analytical#81]
Can I dynamically create new Google Analytics accounts for new websites through API?

**Comment by freerobby** [comment]
Nope, sorry. Unfortunately the Management API only allows listing of existing accounts. See: https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtAccountGuide

You can't create Properties on the fly, either. https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtWebpropertyGuide
